version: '3.7'

services:

  auth-postgres-db:
    container_name: auth-postgres-db
    image: postgres:12-alpine
    ports:
      - "54326:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data


  liquibase:
    container_name: liquibase_changelog_executor
    image: liquibase/liquibase:4.4
    depends_on:
      - auth-postgres-db
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: [ '--driver=org.postgresql.Driver',
               '--url=jdbc:postgresql://auth-postgres-db:5432/postgres',
               '--changeLogFile=changelog/db.changelog-mas.yaml',
               '--username=postgres',
               '--password=postgres',
               '--defaultSchemaName=public',
               'generateChangeLog' ]
    restart: "no"
#  market-postgres-db:
#    container_name: market-postgres-db
#    image: postgres:12-alpine
#    ports:
#      - "54327:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    restart: unless-stopped
#
#  delivery-postgres-db:
#    container_name: delivery-postgres-db
#    image: postgres:12-alpine
#    ports:
#      - "54328:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    restart: unless-stopped
#
#  notification-postgres-db:
#    container_name: notification-postgres-db
#    image: postgres:12-alpine
#    ports:
#      - "54329:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    restart: unless-stopped

